-- Membuat Tabel Mata Kuliah
CREATE TABLE mata_kuliah (
    matkul_id VARCHAR2(10) PRIMARY KEY,
    matkul_nama VARCHAR2(100),
    irs VARCHAR2(50), -- Atribut sesuai permintaan (bisa diisi SKS atau keterangan)
    hari VARCHAR2(20)
);

-- Membuat Tabel IRS dengan Foreign Key
CREATE TABLE irs (
    irs_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matkul_id VARCHAR2(10),
    nim VARCHAR2(50),
    status VARCHAR2(10), -- 'Lulus' atau 'Gagal'
    CONSTRAINT fk_irs_matkul FOREIGN KEY (matkul_id) REFERENCES mata_kuliah(matkul_id),
    CONSTRAINT fk_irs_mahasiswa FOREIGN KEY (nim) REFERENCES mahasiswa(nim)
);

-- Contoh Data untuk Pengetesan (Opsional)
INSERT INTO mata_kuliah VALUES ('MK01', 'Basis Data Terdistribusi', '3 SKS', 'Senin');
INSERT INTO irs (matkul_id, nim, status) VALUES ('MK01', '21120123130102', 'Lulus'); -- Pastikan NIM 12345 ada di tabel mahasiswa